name: Validate

on:
  pull_request:
  push:
  schedule:
    - cron: 30 3 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Validate against Hassfest
        uses: home-assistant/actions/hassfest@master
