name: Validate

on:
  pull_request:
  push:
  schedule:
    - cron: 30 3 * * *

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
        with:
          submodules: recursive
      - name: Validate against Hassfest
        uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658
